# Generated by Django 3.2.11 on 2022-02-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='assignee',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name__in', ['hitman', 'manager'])), on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hit',
            name='creator',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name__in', ['bigboss', 'manager'])), on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
